### ISSUE TITLE
"MVPリリース"レビュー用issue

### ISSUE THREAD

**Issue by yutaotuka** [yutaotuka/Lock-In-Study#58]
## 各種情報
サービス名：Lock In Study
サービスURL：https://lis.fly.dev
GitHub：https://github.com/yutaotuka/Lock-In-Study

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 勉強時間の測定機能　ストップボタンを押したら更新する
- [ ] 勉強時間測定中の質問通知機能　スタートボタンを押して、38分後に通知→5分後に通知に変更
- [ ] LINEでのログイン機能

## READMEレビュー時から変更した機能
追加分
- [ ] ログアウト機能

## サービスイメージがわかるようなスクリーンショット等
* 勉強時間測定中
<img width="840" alt="スクリーンショット 2024-04-08 20 45 22" src="https://github.com/yutaotuka/Lock-In-Study/assets/111165034/0bd3feb7-548a-4832-976f-216bd41244ec">

* 勉強時間測定完了時
<img width="838" alt="スクリーンショット 2024-04-10 17 14 12" src="https://github.com/yutaotuka/Lock-In-Study/assets/111165034/feb8a8b6-f5d0-4553-8dcd-0217622b8211">

* 質問機能
<img width="840" alt="スクリーンショット 2024-04-08 20 46 11" src="https://github.com/yutaotuka/Lock-In-Study/assets/111165034/961adadf-2cc6-43d2-b84c-8167de212d89">

* ログイン機能
<img width="837" alt="スクリーンショット 2024-04-08 20 52 07" src="https://github.com/yutaotuka/Lock-In-Study/assets/111165034/4d6be00f-5959-4cb5-82c6-f174aeb89a6c">

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

---
>  勉強時間測定中の質問通知機能

20分ほどアプリを起動しながら他の作業をしていたのですが、アプリ上に質問が表示されませんでした。
質問はどのタイミングで表示されるのが正しいかお聞きしたいです。

**Comment by yutaotuka** [comment]
説明不足でした。
申し訳ございません。

質問はスタートボタンを押してから38分後にするように設定しております。

**Comment by yutaotuka** [comment]
ご確認ありがとうございます。

測定結果については、現在画面上には表示をしていないため、railsコンソールを立ち上げその中で確認していました。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
