### ISSUE TITLE
中間報告

### ISSUE THREAD

**Issue by yutaotuka** [yutaotuka/Lock-In-Study#80]
## 各種情報
サービス名：Lock In Study
サービスURL：https://www.lockinstudy.com
Github：https://github.com/yutaotuka/Lock-In-Study
プロジェクトURL：https://github.com/users/yutaotuka/projects/3
※現在質問通知が10分に1度されるように設定しています。

### 前回レビュー後実装内容
- [ ] 勉強時間表示ページ（日）
- [ ] 勉強時間表示ページ（週）
- [ ] 回答一覧表示ページ（日）
- [ ] 回答一覧表示ページ（週）
- [ ] 独自ドメイン取得
- [ ] CI構築
- [ ] LINE通知機能実装
- [ ] 静的OGP設定

### 今後の実装予定
- [ ] rspec
- [ ] 利用規約ページ作成
- [ ] プライバシーポリシーページ作成
- [ ] お問い合わせページ作成
- [ ] エラー画面作成
- [ ] CD構築

**Comment by Tsuchiya2** [comment]
お疲れ様です！
以下、サービス触ってのレビューになります。
より良いアプリケーションにするために以下取り組みましょう！

---

■残りのissue消化
・RSpec（モデル・システムテスト）
・素に近いRubocopを通してのリファクタリング
・利用規約
・プライバシーポリシー
・お問い合わせ
・エラー画面

■CI（GitHubActions）
・プッシュされたタイミングで、GitHubActionsを用いてRubocop, RSpecが実行されるように設定しましょう。継続的開発にも関心があることが示せます！（グリーン状態にしておきましょう！）

■時間一覧・回答一覧
・上記に表示されるデータが他者のデータが表示されているようでした。一度確認してみてください！
https://github.com/yutaotuka/Lock-In-Study/assets/61481161/53e522f2-9d81-4f1b-921a-eef925ce8050

■未ログイン時の画面
・未ログイン時の背景グレー部分に、このサービスの使い方を掲載してあげるとユーザー体験が向上するかと！
![image](https://github.com/yutaotuka/Lock-In-Study/assets/61481161/60eef08d-e8f1-446e-8a48-3c4a939172e7)

■コメントの削除
・コード上にあるコメントは削除しましょう！

■scope, クラスメソッドを使う
・answer_index_controller.rbの Anser.select.... などの部分はscopeやクラスメソッドを使って可読性の高い状態にしましょう。

■ファーストページ表示速度改善
・就活中はfly.ioを課金してURLをクリックした際に、現状よりも早く表示されるようにしておくと印象が良いかと思います！

■READMEページ修正
・就活向けにアピールされたREADMEに修正していきましょう！Qiitaの記事や https://fledge-hub.com/ からアピール上手なREADMEを参考にして修正しましょう！
